# Data Encoding 
## 1. Nominal/OHE Encoding 
## 2. Label and Ordinal Encoding 
## 3. Target Guided Ordinal Encoding



## Nominal/OHE Encoding 

One hot encoding, also known as nominal encoding, is a techniqueused to represent categorical data as numerical data, which is more suitable for machine learning algorithms. In this technique, each category is represented as a binary vector where each bit corresponds to a unique category. For example , if we have a categorical value 'Color' with three possible value (red,green,blue), we can represent the one hot encoding as follows :

1. Red:[1,0,0]
2. Green [0,1,0]
3. Blue[0,0,1]

In [3]:
# process of converting Categorical features into Numerical Values , so that the model will be able to understand for a specific purpose .

In [5]:
# in one hot encoding there is a major setback that if we have 100 types of categories then we need to create 100 no.of features.
# this is sparse matrix also. (Overfitting)
# so we can't be ablw to use one hot encoding when we have maximum variance.

In [6]:
import pandas as pd
from sklearn.preprocessing import OneHotEncoder

In [9]:
# create a simple dataframe 
df = pd.DataFrame({
    'color' : ['red','blue','green','green','red','blue']
}
)

In [10]:
df.head()

   color
0    red
1   blue
2  green
3  green
4    red

In [11]:
## create ab instance of one hot encoder 
encoder=OneHotEncoder()

In [18]:
## perform fit and transform
encoded=encoder.fit_transform(df[['color']]).toarray() # here we converted and we cab see that it is basically based upon the alphabetical order 
## first should be Blue, then Green after that Red.
## this is how we probably create this.

In [23]:
import pandas as pd
encoder_df=pd.DataFrame(encoded,columns=encoder.get_feature_names_out())

In [24]:
encoder_df

   color_blue  color_green  color_red
0         0.0          0.0        1.0
1         1.0          0.0        0.0
2         0.0          1.0        0.0
3         0.0          1.0        0.0
4         0.0          0.0        1.0
5         1.0          0.0        0.0

In [25]:
## so in this way we are basically converting a categorical features into numerical features.

In [30]:
## suppose you have got a new data then how it will happen ? 
encoder.transform([['blue']]).toarray()
# for new data

C:\New folder\Lib\site-packages\sklearn\utils\validation.py:2827: UserWarning: X does not have valid feature names, but OneHotEncoder was fitted with feature names
  warnings.warn(

array([[1., 0., 0.]])

In [31]:
pd.concat([df,encoder_df],axis=1)

   color  color_blue  color_green  color_red
0    red         0.0          0.0        1.0
1   blue         1.0          0.0        0.0
2  green         0.0          1.0        0.0
3  green         0.0          1.0        0.0
4    red         0.0          0.0        1.0
5   blue         1.0          0.0        0.0

In [33]:
### one internal assignment 

import seaborn as sns
sns.load_dataset('tips')

     total_bill   tip     sex smoker   day    time  size
0         16.99  1.01  Female     No   Sun  Dinner     2
1         10.34  1.66    Male     No   Sun  Dinner     3
2         21.01  3.50    Male     No   Sun  Dinner     3
3         23.68  3.31    Male     No   Sun  Dinner     2
4         24.59  3.61  Female     No   Sun  Dinner     4
..          ...   ...     ...    ...   ...     ...   ...
239       29.03  5.92    Male     No   Sat  Dinner     3
240       27.18  2.00  Female    Yes   Sat  Dinner     2
241       22.67  2.00    Male    Yes   Sat  Dinner     2
242       17.82  1.75    Male     No   Sat  Dinner     2
243       18.78  3.00  Female     No  Thur  Dinner     2

[244 rows x 7 columns]

In [38]:
df = sns.load_dataset('tips')
df

     total_bill   tip     sex smoker   day    time  size
0         16.99  1.01  Female     No   Sun  Dinner     2
1         10.34  1.66    Male     No   Sun  Dinner     3
2         21.01  3.50    Male     No   Sun  Dinner     3
3         23.68  3.31    Male     No   Sun  Dinner     2
4         24.59  3.61  Female     No   Sun  Dinner     4
..          ...   ...     ...    ...   ...     ...   ...
239       29.03  5.92    Male     No   Sat  Dinner     3
240       27.18  2.00  Female    Yes   Sat  Dinner     2
241       22.67  2.00    Male    Yes   Sat  Dinner     2
242       17.82  1.75    Male     No   Sat  Dinner     2
243       18.78  3.00  Female     No  Thur  Dinner     2

[244 rows x 7 columns]

In [39]:
encoded_01=encoder.fit_transform(df[['smoker']]).toarray()

In [40]:
encoded_01

array([[1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [0., 1.],
       [1., 0.],
       [0., 1.],
       [1., 0.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [0., 1.],
       [1., 0.],
       [0., 1.],
       [1., 0.],
       [1., 0.],
       [0., 1.],
       [0., 1.],
       [1., 0.],
       [1., 0.],
       [0., 1.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [0., 1.],
       [1., 0.],
       [1., 0.],
       [0., 1.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [0., 1.],
       [1., 0.],
       [0., 1.],
       [0., 1.],
       [1., 0.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [1., 0.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [1., 0.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [1., 0.],
       [0., 1.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [0., 1.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [0., 1.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [1., 0.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [1., 0.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [1., 0.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [1., 0.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [1., 0.],
       [1., 0.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [1., 0.],
       [1., 0.],
       [0., 1.],
       [1., 0.],
       [0., 1.],
       [0., 1.],
       [1., 0.],
       [1., 0.],
       [0., 1.],
       [0., 1.],
       [1., 0.],
       [1., 0.]])

In [44]:
encoder_df=pd.DataFrame(encoded_01,columns=encoder.get_feature_names_out())

In [45]:
encoder_df

     smoker_No  smoker_Yes
0          1.0         0.0
1          1.0         0.0
2          1.0         0.0
3          1.0         0.0
4          1.0         0.0
..         ...         ...
239        1.0         0.0
240        0.0         1.0
241        0.0         1.0
242        1.0         0.0
243        1.0         0.0

[244 rows x 2 columns]

In [46]:
pd.concat([df,encoder_df],axis=1)

,total_bill,tip,sex,smoker,day,time,size,smoker_No,smoker_Yes
0,16.99,1.01,Female,No,Sun,Dinner,2,1.0,0.0
1,10.34,1.66,Male,No,Sun,Dinner,3,1.0,0.0
2,21.01,3.50,Male,No,Sun,Dinner,3,1.0,0.0
3,23.68,3.31,Male,No,Sun,Dinner,2,1.0,0.0
4,24.59,3.61,Female,No,Sun,Dinner,4,1.0,0.0
...,...,...,...,...,...,...,...,...,...
239,29.03,5.92,Male,No,Sat,Dinner,3,1.0,0.0
240,27.18,2.00,Female,Yes,Sat,Dinner,2,0.0,1.0
241,22.67,2.00,Male,Yes,Sat,Dinner,2,0.0,1.0
242,17.82,1.75,Male,No,Sat,Dinner,2,1.0,0.0
243,18.78,3.00,Female,No,Thur,Dinner,2,1.0,0.0

## Label Encoding 

Label encoding and ordinal encoding are two techniques used to encode categorical data vs numerical data.

Label encoding involves assigning a unique numerical label to each category in the variable. The labels are usually assigned in alphabetical order on based on the frequency of the categories. For example, if we have a categorical variable 'color' with three possible values (red,green,blue), we can represent it using label encoding as follows:

1.Red : 1
2.Green: 2
3. Blue: 3

In [47]:
# create a simple dataframe 
df = pd.DataFrame({
    'color' : ['red','blue','green','green','red','blue']
}
)

In [48]:
df.head()

   color
0    red
1   blue
2  green
3  green
4    red

In [49]:
from sklearn.preprocessing import LabelEncoder
lbl_encoder=LabelEncoder()

In [50]:
lbl_encoder.fit_transform(df[['color']])

C:\New folder\Lib\site-packages\sklearn\preprocessing\_label.py:120: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)

array([2, 0, 1, 1, 2, 0])

In [51]:
lbl_encoder.transform([['red']])

C:\New folder\Lib\site-packages\sklearn\preprocessing\_label.py:139: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, dtype=self.classes_.dtype, warn=True)

array([2])

In [53]:
lbl_encoder.transform([['green']])

C:\New folder\Lib\site-packages\sklearn\preprocessing\_label.py:139: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, dtype=self.classes_.dtype, warn=True)

array([1])

In [54]:
## see here the major issue we will face that here due to the numerical values like 0,1,2 for blue green and red when we build machine learning 
# models then e=there is a chance of getting the value of Red as a high because it has 2 or else green has a high compare to blue .. so we need to use this label 
# encoder when there will be the rank based assignment happens .

### Ordinal Encoding 

it is used to encode categorical data that have an intrinsic order or ranking. In this technique, eah category us assigned a numerical value based on its position in the order. For example, if we have a categorical variable "education level" with four possibles values (high school, college,graduate, post-graduate), We can represent it using ordinal coding as follows:

1.High School: 1
2.College:2
3.Graduate: 3
4.Post-Graduate : 4

In [55]:
## ordinal encoding 
from sklearn.preprocessing import OrdinalEncoder

In [56]:
# create a simple dataframe 
df = pd.DataFrame({
    'size': ['small','medium','large','medium','small','large']
})

In [57]:
df

     size
0   small
1  medium
2   large
3  medium
4   small
5   large

In [58]:
## create an instance of ordinal encoder and then fit_tranform 
encoder=OrdinalEncoder(categories=[['small','medium','large']])

In [60]:
encoder.fit_transform(df[['size']])

array([[0.],
       [1.],
       [2.],
       [1.],
       [0.],
       [2.]])

In [61]:
encoder.transform([['small']])

C:\New folder\Lib\site-packages\sklearn\utils\validation.py:2827: UserWarning: X does not have valid feature names, but OrdinalEncoder was fitted with feature names
  warnings.warn(

array([[0.]])

### Target Guided Ordinal Encoding 

It is a technique used to encode categorical variables based on their relationship with the target variable. This encoding technique is useful when we have a categorical variable with a large number of unique categories, and we want to use this variable as a feature in our machine learning model.

in Target Guided Ordinal Encoding , we replace each category in the categorical variable with a numerical value based on the mean or median of the target variable of this category. This creates a monotonic relationship between the categorical variable and the target variable, which can improve the predictive power of our model

In [63]:
import pandas as pd 

# create a sample dataframe with a categorical variable and a target c=variable 
df = pd.DataFrame({
    'city': ['New York','London','Paris','Tokyo','New York','Paris'],
    'price': [200,150,300,250,100,320]
})

In [65]:
df # here price is a target variable based on this target varibale we will try to convert this categorical feature into 
# based on this target variable.

       city  price
0  New York    200
1    London    150
2     Paris    300
3     Tokyo    250
4  New York    100
5     Paris    320

In [68]:
mean_price=df.groupby('city')['price'].mean().to_dict()

In [69]:
mean_price

{'London': 150.0, 'New York': 150.0, 'Paris': 310.0, 'Tokyo': 250.0}

In [70]:
df['city_encoded']=df['city'].map(mean_price)

In [71]:
df

       city  price  city_encoded
0  New York    200         150.0
1    London    150         150.0
2     Paris    300         310.0
3     Tokyo    250         250.0
4  New York    100         150.0
5     Paris    320         310.0

In [72]:
df[['city','city_encoded']]

       city  city_encoded
0  New York         150.0
1    London         150.0
2     Paris         310.0
3     Tokyo         250.0
4  New York         150.0
5     Paris         310.0

In [85]:
## internal assignment :  do the task same as you have done but this time take the tips dataset one feature time based on the total_bill  
import seaborn as sns 
df = sns.load_dataset('tips')

In [86]:
df

     total_bill   tip     sex smoker   day    time  size
0         16.99  1.01  Female     No   Sun  Dinner     2
1         10.34  1.66    Male     No   Sun  Dinner     3
2         21.01  3.50    Male     No   Sun  Dinner     3
3         23.68  3.31    Male     No   Sun  Dinner     2
4         24.59  3.61  Female     No   Sun  Dinner     4
..          ...   ...     ...    ...   ...     ...   ...
239       29.03  5.92    Male     No   Sat  Dinner     3
240       27.18  2.00  Female    Yes   Sat  Dinner     2
241       22.67  2.00    Male    Yes   Sat  Dinner     2
242       17.82  1.75    Male     No   Sat  Dinner     2
243       18.78  3.00  Female     No  Thur  Dinner     2

[244 rows x 7 columns]

In [87]:
df.head()

   total_bill   tip     sex smoker  day    time  size
0       16.99  1.01  Female     No  Sun  Dinner     2
1       10.34  1.66    Male     No  Sun  Dinner     3
2       21.01  3.50    Male     No  Sun  Dinner     3
3       23.68  3.31    Male     No  Sun  Dinner     2
4       24.59  3.61  Female     No  Sun  Dinner     4

In [88]:
df.columns

Index(['total_bill', 'tip', 'sex', 'smoker', 'day', 'time', 'size'], dtype='object')

In [90]:
new_df=df[['time', 'total_bill']]

In [91]:
new_df

       time  total_bill
0    Dinner       16.99
1    Dinner       10.34
2    Dinner       21.01
3    Dinner       23.68
4    Dinner       24.59
..      ...         ...
239  Dinner       29.03
240  Dinner       27.18
241  Dinner       22.67
242  Dinner       17.82
243  Dinner       18.78

[244 rows x 2 columns]

In [102]:
mean_price_of_total_bill=df.groupby('time')['total_bill'].mean()

C:\Users\ganes\AppData\Local\Temp\ipykernel_29632\2384257585.py:1: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  mean_price_of_total_bill=df.groupby('time')['total_bill'].mean()

In [103]:
mean_price_of_total_bill

time
Lunch     17.168676
Dinner    20.797159
Name: total_bill, dtype: float64

In [105]:
df['time'].map(mean_price_of_total_bill)

0      20.797159
1      20.797159
2      20.797159
3      20.797159
4      20.797159
         ...
239    20.797159
240    20.797159
241    20.797159
242    20.797159
243    20.797159
Name: time, Length: 244, dtype: category
Categories (2, float64): [17.168676, 20.797159]

In [101]:
df

     total_bill   tip     sex smoker   day    time  size  time_encoded
0         16.99  1.01  Female     No   Sun  Dinner     2           NaN
1         10.34  1.66    Male     No   Sun  Dinner     3           NaN
2         21.01  3.50    Male     No   Sun  Dinner     3           NaN
3         23.68  3.31    Male     No   Sun  Dinner     2           NaN
4         24.59  3.61  Female     No   Sun  Dinner     4           NaN
..          ...   ...     ...    ...   ...     ...   ...           ...
239       29.03  5.92    Male     No   Sat  Dinner     3           NaN
240       27.18  2.00  Female    Yes   Sat  Dinner     2           NaN
241       22.67  2.00    Male    Yes   Sat  Dinner     2           NaN
242       17.82  1.75    Male     No   Sat  Dinner     2           NaN
243       18.78  3.00  Female     No  Thur  Dinner     2           NaN

[244 rows x 8 columns]